import random


def guess_num(x):

    print("===================================")
    print("Welcome to the number guessing game!")
    print("===================================")
    print("Your goal is to guess the number generated by the computer.")

    random_number = random.randint(1, x)  # random number between 1 and x

    prediction = 0

    while prediction != random_number:
        prediction = int(input(f"Guess a number between 1 and {x}: "))

        if prediction < random_number:
            print("Try again. Your guess is too low.")
        elif prediction > random_number:
            print("Try again. Your guess is too high.")

    print(
        f"Congratulations! You guessed the number {random_number} correctly!")


guess_num(10)
